
<div class="container">
  <h2>Welcome Admin</h2>
  <ul class="nav nav-tabs">
    <li class="active"><a data-toggle="tab" href="#projects">Projects</a></li>
    <li><a data-toggle="tab" href="#my_teams">My Teams</a></li>
  </ul>

  <div class="tab-content">
    <div id="projects" class="tab-pane fade in active">  
	  	<h2>Projects</h2>
	  	<p><?php $this->flashSession->output() ?></p>	
		<button type="button" class="btn btn-info btn-sm" data-toggle="modal" data-target="#modalCreateProject">Create Project</button>           
		
		<table class="table table-hover">
		    <thead>
		      <tr>
		        <th>Project Name</th>
		        <th>Description</th>
		        <th>Team</th>
		        <th>Status</th>
		        <th>Action</th>
		      </tr>
		    </thead>
		    <tbody>
		    <?php foreach ($projects as $project) { ?>
		      <tr>
		        <td><a href="<?=BASE_URI.'projects/'.$project->name.'/'.md5($project->project_id)?>"><?=ucfirst($project->name)?></a></td>
		        <td><?=ucfirst($project->description)?></td>
		        <td>
		        	<?php $project_teams = ProjectTeam::listTeams($project->project_id); ?>
			       	<?php foreach ($project_teams as $team) { ?>
			       	<a href="#"><?=$team->name?></a><br>
			       	<?php } ?>
		        </td>
		        <td><?=ucfirst($project->status_name)?></td>
		        <td><button type="button" class="btn btn-info btn-sm">Edit</button></td>		   
		      </tr>
		    <?php } ?>
		    </tbody>
		</table>
    </div>
    
    <div id="my_teams" class="tab-pane fade">
      	<h2>My Teams</h2>
  		<button type="button" class="btn btn-info btn-sm" data-toggle="modal" data-target="#modalCreateTeam">Create New Team</button>     
		<button type="button" class="btn btn-info btn-sm">Edit Team</button>     
		<button type="button" class="btn btn-danger btn-sm">Delete Team</button>      
  		<table class="table table-hover">
		    <thead>
		      <tr>
		        <th>Team Name</th>
		        <th>Description</th>
		        <th>Members</th>
		        <th>Status</th>
		        <th>Action</th>
		      </tr>
		    </thead>
		    <tbody>
		    <?php foreach ($teams as $team) { ?>
		      <tr>
		        <td><?=$team->team_name?></td>
		        <td><?=$team->description?></td>
		        
		        <td>
			       	<?php $members = TeamMembers::listMembers($team->team_id); ?>
			       	<?php foreach ($members as $member) { ?>
			       	<a href="#"><?=$member->username?></a><br>
			       	<?php } ?>
		        </td>
		        <td><?=ucfirst($team->status_name)?></td>
		        <td><button type="button" class="btn btn-info btn-sm">Edit</button></td>
		      </tr>
		     <?php } ?>
		    </tbody>
	  	</table>
    </div>
  </div>
</div>

