<div class="modal fade" id="modalCreateAccount">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Create New Account</h4>
      </div>
      <div class="modal-body">
         <form id="frmCreateAccount"role="form" method="post" action="<?=BASE_URI?>post/createAccount">
         <div id="remarks"></div>
        
              <div class="form-group">
                <label for="email">Username:</label>
                <input name = "username" type="text" class="form-control"  placeholder="Enter username" required data-error="Username is required">
              </div>
              <div class="form-group">
                <label for="pwd">Usertype:</label>
                 <select class="form-control" name="user_type_id" required>
                  <?php foreach ($user_types as $value) { ?>
                    <option value="<?=$value->id?>"><?=ucfirst($value->name)?></option>
                  <?php }?>
                </select>
              </div>
         
      </div>
      <div class="modal-footer">
        <button id="btnClose" type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button id="btnCreateAccount" type="submit" class="btn btn-primary">Save changes</button>
      </div>
      </form>
      </div> <!-- /.modal-body -->
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div class="modal fade" id="modalConfirm">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Modal title</h4>
      </div>
      <div class="modal-body">
         <form id="frmCreateAccount"role="form" method="post" action="<?=BASE_URI?>post/createAccount">
              
              <div class="form-group">
                <label for="email">Username:</label>
                <input name = "username" type="text" class="form-control"  placeholder="Enter username" required data-error="Username is required">
              </div>
              <div class="form-group">
                <label for="pwd">Usertype:</label>
                 <select class="form-control" name="user_type_id" required>
                  <?php foreach ($user_types as $value) { ?>
                    <option value="<?=$value->id?>"><?=ucfirst($value->name)?></option>
                  <?php }?>
                </select>
              </div>
         
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button id="btnCreateAccount" type="submit" class="btn btn-primary">Save changes</button>
      </div>
      </form>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

