<div class="modal fade" id="modalCreateTeam">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Create New Team</h4>
      </div>
      <div class="modal-body">
         <form id="frmCreateTeam"role="form" method="post">
         <div id="remarks"></div>
        
              <div class="form-group">
                <label for="team_name">Team Name:</label>
                <input name = "name" type="text" class="form-control"  placeholder="Enter Team Name" required data-error="Username is required">
              </div>
              <div class="form-group">
                <label for="description" >Description:</label>
                <textarea placeholder="Enter Description"  name="description" class="form-control" rows="5" id="description" required></textarea>
              </div>
              <div class="form-group">
                <label for="team_name">Members:</label>
                <select name="members[]" required class="js-example-basic-multiple form-control" style="width: 100%" multiple="multiple">
                <?php foreach ($members as $value) { ?>
                  <option  value="<?=$value->id?>"><?=$value->username?></option>
                <?php } ?>
                </select>
              </div>
         
      </div>
      <div class="modal-footer">
        <button id="btnClose" type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button id="btnCreateTeam" type="submit" class="btn btn-primary">Save changes</button>
      </div>
      </form>
      </div> <!-- /.modal-body -->
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


<div class="modal fade" id="modalCreateProject">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Create New Team</h4>
      </div>
      <div class="modal-body">
         <form id="frmCreateProject" role="form" method="post">
         <div id="remarks"></div>
        
              <div class="form-group">
                <label for="team_name">Project Name:</label>
                <input name = "name" type="text" class="form-control"  placeholder="Enter Project Name" required data-error="Username is required">
              </div>
              <div class="form-group">
                <label for="description" >Description:</label>
                <textarea placeholder="Enter Description"  name="description" class="form-control" rows="5" id="description" required></textarea>
              </div>
              <div class="form-group">
                <label for="team_name">Teams:</label>
                <select name="teams[]" required class="js-example-basic-multiple form-control" style="width: 100%" multiple="multiple">
                <?php foreach ($teams as $team) { ?>
                  <option  value="<?=$team->team_id?>"><?=$team->team_name?></option>
                <?php } ?>
                </select>
              </div>
         
      </div>
      <div class="modal-footer">
        <button id="btnCloseCreateProject" type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button id="btnCreateTeam" type="submit" class="btn btn-primary">Save changes</button>
      </div>
      </form>
      </div> <!-- /.modal-body -->
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


