<!-- Static navbar -->
<div class="navbar navbar-fixed-top navbar-default">
<div class="navbar-header">
  <button type="button" class="navbar-toggle" data-toggle="offcanvas" data-target=".navbar-offcanvas" data-canvas="body">
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </button>
  <a class="navbar-brand" href="#">Task Manager</a>
</div>
<div class="navbar-offcanvas offcanvas">
  
  <ul class="nav navbar-nav">
    <li class="active"><a href="<?=BASE_URI?>master/home">Home</a></li>
    <li><a href="#">Projects</a></li>
    <li><a href="#">Notifications</a></li>
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account Settings<b class="caret"></b></a>
      <ul class="dropdown-menu">
        <li><a href="#">Change Password</a></li>
        <li class="divider"></li>
        <li><a href="<?=BASE_URI?>admin/logout">Log out</a></li>
      </ul>
    </li>
  </ul>
</div><!--/.nav-collapse -->
</div>
