<div class="container col-sm-4 col-centered">
  <h2>Welcome to Task Manager</h2>
  <h3>Login Form </h3>
  <form role="form" method="post" action="<?=BASE_URI?>post/login">
  	<p><?php $this->flashSession->output() ?></p>
    <div class="form-group">
      <label for="email">Username:</label>
      <input name = "username" type="text" class="form-control"  placeholder="Enter username" required data-error="Username is required">
    </div>
    <div class="form-group">
      <label for="pwd">Password:</label>
      <input name="password" type="password" class="form-control" id="pwd" placeholder="Enter password" required>
    </div>
    <div class="checkbox">
      <label><input type="checkbox"> Remember me</label>
    </div>
    <button type="submit" class="btn btn-default">Submit</button>
  </form>
</div>
