<!DOCTYPE html>
<html>
	<head>
		<title>Webbit Task Manager</title>
		<meta charset="utf-8">
	 	<meta name="viewport" content="width=device-width, initial-scale=1">
	  	<?php $this->assets->outputCss('global_header_css') ?>
	  	<?php $this->assets->outputJs('global_header_js') ?>
	</head>
	<body>
		<?php $this->partial('common/admin_menu'); ?>
		<?php $this->partial($page_content); ?>
	 	<?php $this->partial('common/admin_modals'); ?>
	 	<script type="text/javascript">
	 	var URL = "<?php echo BASE_URI; ?>";
		var CURR_DATE = "<?php echo CURR_DATE ?>";
		</script>
	 	<?php $this->assets->outputJs('admin_js') ?>
	</body>
</html>