
<div class="container">
  <h2>Checkapp</h2>

  <h3> Task List <button type="button" class="btn btn-info btn-sm" data-toggle="modal" data-target="#modalCreateTasks">Create Task</button> </h3>

  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Notes</th>
        <th>Links</th>
        <th>Severity</th>
        <th>Status</th>
        <th>Due Date</th>
        <th>Priority</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <tr class="success">
        <td>John</td>
        <td>Paki bilis</td>
        <td>john@example.com</td>
        <td>Mild</td>
        <td>On Progress</td>
        <td>Nov 12, 1988</td>
        <td>High</td>
        <td>john@example.com</td>
      </tr>
      <tr class="danger">
        <td>John</td>
        <td>Doe</td>
        <td>john@example.com</td>
        <td>john@example.com</td>
        <td>john@example.com</td>
        <td>john@example.com</td>
        <td>john@example.com</td>
      </tr>
      <tr class="info">
        <td>John</td>
        <td>Doe</td>
        <td>john@example.com</td>
        <td>john@example.com</td>
        <td>john@example.com</td>
        <td>john@example.com</td>
        <td>john@example.com</td>
      </tr>
    </tbody>
  </table>
</div>


